Hackathon/Models/ErrorViewModel.cs
using System;

namespace Hackathon.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hackathon/Models/Vagas.cs
using System;

namespace Hackathon.Models
{
    public class Vagas
    {
        public Vagas(
            Guid id,
            string imagem,
            string local,
            string distancia,
            int rate)
        {
            Id = id;
            Imagem = imagem;
            Local = local;
            Distancia = distancia;
            Rate = rate;
        }

        public Guid Id { get; set; }
        public string Imagem { get; set; }
        public string Local { get; set; }
        public string Distancia { get; set; }
        public int Rate { get; set; }
    }
}

Hackathon/Controllers/ChegaAquiController.cs
using Hackathon.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace Hackathon.Controllers
{
    public class ChegaAquiController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.VagasNaoOcupadas = 50;
            ViewBag.VagasOcupadas = 75;

            return View();
        }

        public IActionResult Login()
        {
            ViewBag.VagasNaoOcupadas = 50;
            ViewBag.VagasOcupadas = 75;

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult GaragemIndex()
        {
            return View();
        }

        public IActionResult ClienteIndex(string pesquisa)
        {
            var lista = new List<Vagas>();
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Quinze de novembro", "200m", 5));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Dr. Amadeu da Luz", "300m", 4));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Pres. John Kenedy", "250m", 5));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Ingo Hering", "350m", 5));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Pres. Getúlio Vargas", "300m", 4));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Ângelo Dias", "250m", 5));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Eng. Rodolfo Ferraz", "450m", 5));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. São Paulo", "500m", 5));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Mal. Floriano Peixoto", "500m", 4));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Alameda Rio Branco", "400m", 3));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. R. Dr. Luiz de Freitas Melro", "500m", 4));
            lista.Add(new Vagas(Guid.NewGuid(), null, "Centro, R. Antônio da Veiga", "1,3km", 5));
            if (pesquisa == null)
                return View(lista);
            var listaFiltrada = lista.Where(x => x.Local.Contains(pesquisa)).ToList();
            return View(listaFiltrada);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hackathon/Views/ChegaAqui/ClienteIndex.cshtml
@model IEnumerable<Hackathon.Models.Vagas>

    @{
    ViewData["Title"] = "ClienteIndex";
    }

    <div class="input-field col s6">
        @using (Html.BeginForm("ClienteIndex", "ChegaAqui", FormMethod.Get))
        {
        <div class="input-field col s6">
            @Html.TextBox("Pesquisa", null, new { id = "pesquisa", placeholder = "Placeholder" })
            <label for="pesquisa">Busca</label>
        </div>
        }
    </div>

    @foreach (var item in Model)
    {
    <div class="row">
        <div class="col s12 m6">
            <div class="card">
                <div class="display-flex">
                    <img src="~/lib/imagens/imagem.png" class="imagem ">
                    <div class="card-content white-text">
                        <h6>Local: @item.Local </h6>
                        <h6>Avaliação: @item.Rate </h6>
                        <h6>Distancia: @item.Distancia </h6>
                    </div>
                </div>
                <div class="card-action">
                    <a asp-action="ChegaAqui" class="btn grey lighten-1">Reservar<i id="check" class="small material-icons">check</i></a>
                    <a asp-action="ChegaAqui" class="btn grey lighten-1">Detalhes<i id="detalhes" class="small material-icons">info</i></a>
                </div>
            </div>
        </div>
    </div>

    }

Hackathon/Views/ChegaAqui/GaragemIndex.cshtml
@{
    ViewData["Title"] = "GaragemIndex";
}

<div class="card-panel grey darken-3" align="center"><b>Nome do Estacionamento:</b><p>Estacionamento Alfa</p></div>
<div class="card-panel grey darken-3" align="center"><b>Endereço do estacionamento: </b><p>R. 7 de Setembro, 1817 - Centro, Blumenau - SC, 89010-202</p></div>
<div class="card-panel grey darken-3" align="center"><b>Contato: </b><p>(47) 99153-2270</p></div>
<div class="card-panel grey darken-3" align="center"><b>Valor: </b><p>R$4,00 /h</p></div>
<div class="card-panel grey darken-3" align="center"><b>Suas vagas disponíves são:</b><p> 50</p></div>
<div class="card-panel grey darken-3" align="center"><b>Suas vagas ocupadas são:</b><p> 50</p></div>
<div class="card-panel grey darken-3" align="center"><b>Total de vagas na garagem:</b><p> 100</p></div>

Hackathon/Views/ChegaAqui/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <span class="flow-text">Bem Vindo !!! </span>

    <div class="row">
        <div class="col s12 m6">
            <div class="card grey darken-1">
                <div class="card-content white-text">
                    <span class="flow-text">Você tem @ViewBag.VagasNaoOcupadas vagas não ocupadas</span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m6">
            <div class="card grey darken-1">
                <div class="card-content white-text">
                    <span class="flow-text">Você tem @ViewBag.VagasOcupadas vagas ocupadas</span>
                </div>
            </div>
        </div>
    </div>
</div>

Hackathon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hackathon</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>
    <header>
        <nav>
            <div class="nav-wrapper black">
                <a href="#" class="brand-logo center"><img src="~/lib/imagens/chega_aqui.png" /></a>
                <ul id="nav-mobile" class="left hide-on-med-and-down ">
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Contato</a></li>
                </ul>
                <ul id="nav-mobile" class="right hide-on-med-and-down ">
                    <li><a href="#">Sair</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">

        @RenderBody()
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>